-- Mechanically realizes HONOR_DB_ACCESS_MATRIX.json.
REVOKE CREATE ON SCHEMA public FROM honor_app;
GRANT USAGE ON SCHEMA public TO honor_app;
ALTER TABLE social_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE social_identities FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE social_identities FROM PUBLIC;
REVOKE ALL ON TABLE social_identities FROM honor_app;
ALTER TABLE social_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE social_accounts FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE social_accounts FROM PUBLIC;
REVOKE ALL ON TABLE social_accounts FROM honor_app;
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE campaigns FROM PUBLIC;
REVOKE ALL ON TABLE campaigns FROM honor_app;
ALTER TABLE uploads ENABLE ROW LEVEL SECURITY;
ALTER TABLE uploads FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE uploads FROM PUBLIC;
REVOKE ALL ON TABLE uploads FROM honor_app;
ALTER TABLE sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE sources FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE sources FROM PUBLIC;
REVOKE ALL ON TABLE sources FROM honor_app;
ALTER TABLE transcripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE transcripts FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE transcripts FROM PUBLIC;
REVOKE ALL ON TABLE transcripts FROM honor_app;
ALTER TABLE generation_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE generation_runs FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE generation_runs FROM PUBLIC;
REVOKE ALL ON TABLE generation_runs FROM honor_app;
ALTER TABLE clips ENABLE ROW LEVEL SECURITY;
ALTER TABLE clips FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE clips FROM PUBLIC;
REVOKE ALL ON TABLE clips FROM honor_app;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE posts FROM PUBLIC;
REVOKE ALL ON TABLE posts FROM honor_app;
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE submissions FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE submissions FROM PUBLIC;
REVOKE ALL ON TABLE submissions FROM honor_app;
ALTER TABLE analytics_checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_checkins FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE analytics_checkins FROM PUBLIC;
REVOKE ALL ON TABLE analytics_checkins FROM honor_app;
ALTER TABLE polli_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE polli_sessions FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE polli_sessions FROM PUBLIC;
REVOKE ALL ON TABLE polli_sessions FROM honor_app;
ALTER TABLE owner_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE owner_actions FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE owner_actions FROM PUBLIC;
REVOKE ALL ON TABLE owner_actions FROM honor_app;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE jobs FROM PUBLIC;
REVOKE ALL ON TABLE jobs FROM honor_app;
ALTER TABLE api_idempotency_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_idempotency_records FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE api_idempotency_records FROM PUBLIC;
REVOKE ALL ON TABLE api_idempotency_records FROM honor_app;
ALTER TABLE experiments ENABLE ROW LEVEL SECURITY;
ALTER TABLE experiments FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE experiments FROM PUBLIC;
REVOKE ALL ON TABLE experiments FROM honor_app;
ALTER TABLE experiment_arms ENABLE ROW LEVEL SECURITY;
ALTER TABLE experiment_arms FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE experiment_arms FROM PUBLIC;
REVOKE ALL ON TABLE experiment_arms FROM honor_app;
ALTER TABLE experiment_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE experiment_assignments FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE experiment_assignments FROM PUBLIC;
REVOKE ALL ON TABLE experiment_assignments FROM honor_app;
ALTER TABLE account_health_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE account_health_snapshots FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE account_health_snapshots FROM PUBLIC;
REVOKE ALL ON TABLE account_health_snapshots FROM honor_app;
ALTER TABLE campaign_terms_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_terms_snapshots FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE campaign_terms_snapshots FROM PUBLIC;
REVOKE ALL ON TABLE campaign_terms_snapshots FROM honor_app;
ALTER TABLE qc_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_runs FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE qc_runs FROM PUBLIC;
REVOKE ALL ON TABLE qc_runs FROM honor_app;
ALTER TABLE analytics_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_observations FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE analytics_observations FROM PUBLIC;
REVOKE ALL ON TABLE analytics_observations FROM honor_app;
ALTER TABLE provider_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE provider_usage FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE provider_usage FROM PUBLIC;
REVOKE ALL ON TABLE provider_usage FROM honor_app;
ALTER TABLE polli_turns ENABLE ROW LEVEL SECURITY;
ALTER TABLE polli_turns FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE polli_turns FROM PUBLIC;
REVOKE ALL ON TABLE polli_turns FROM honor_app;
ALTER TABLE polli_tool_calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE polli_tool_calls FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE polli_tool_calls FROM PUBLIC;
REVOKE ALL ON TABLE polli_tool_calls FROM honor_app;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE events FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE events FROM PUBLIC;
REVOKE ALL ON TABLE events FROM honor_app;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE audit_log FROM PUBLIC;
REVOKE ALL ON TABLE audit_log FROM honor_app;
ALTER TABLE edit_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE edit_plans FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE edit_plans FROM PUBLIC;
REVOKE ALL ON TABLE edit_plans FROM honor_app;
ALTER TABLE audio_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE audio_plans FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE audio_plans FROM PUBLIC;
REVOKE ALL ON TABLE audio_plans FROM honor_app;
ALTER TABLE render_manifests ENABLE ROW LEVEL SECURITY;
ALTER TABLE render_manifests FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE render_manifests FROM PUBLIC;
REVOKE ALL ON TABLE render_manifests FROM honor_app;
ALTER TABLE campaign_rule_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_rule_items FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE campaign_rule_items FROM PUBLIC;
REVOKE ALL ON TABLE campaign_rule_items FROM honor_app;
ALTER TABLE run_campaign_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE run_campaign_allocations FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE run_campaign_allocations FROM PUBLIC;
REVOKE ALL ON TABLE run_campaign_allocations FROM honor_app;
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidates FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE candidates FROM PUBLIC;
REVOKE ALL ON TABLE candidates FROM honor_app;
ALTER TABLE restriction_proof_artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE restriction_proof_artifacts FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE restriction_proof_artifacts FROM PUBLIC;
REVOKE ALL ON TABLE restriction_proof_artifacts FROM honor_app;
ALTER TABLE owner_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE owner_profiles FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE owner_profiles FROM PUBLIC;
REVOKE ALL ON TABLE owner_profiles FROM honor_app;
ALTER TABLE audio_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE audio_assets FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE audio_assets FROM PUBLIC;
REVOKE ALL ON TABLE audio_assets FROM honor_app;
ALTER TABLE backup_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE backup_runs FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE backup_runs FROM PUBLIC;
REVOKE ALL ON TABLE backup_runs FROM honor_app;
ALTER TABLE cost_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE cost_ledger FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE cost_ledger FROM PUBLIC;
REVOKE ALL ON TABLE cost_ledger FROM honor_app;
ALTER TABLE source_rights ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_rights FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE source_rights FROM PUBLIC;
REVOKE ALL ON TABLE source_rights FROM honor_app;
ALTER TABLE source_rights_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_rights_campaigns FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE source_rights_campaigns FROM PUBLIC;
REVOKE ALL ON TABLE source_rights_campaigns FROM honor_app;
ALTER TABLE earnings ENABLE ROW LEVEL SECURITY;
ALTER TABLE earnings FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE earnings FROM PUBLIC;
REVOKE ALL ON TABLE earnings FROM honor_app;
ALTER TABLE earning_state_transitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE earning_state_transitions FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE earning_state_transitions FROM PUBLIC;
REVOKE ALL ON TABLE earning_state_transitions FROM honor_app;
ALTER TABLE campaign_rule_set_commits ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_rule_set_commits FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE campaign_rule_set_commits FROM PUBLIC;
REVOKE ALL ON TABLE campaign_rule_set_commits FROM honor_app;
ALTER TABLE accepted_edit_signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE accepted_edit_signatures FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE accepted_edit_signatures FROM PUBLIC;
REVOKE ALL ON TABLE accepted_edit_signatures FROM honor_app;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon'; END IF; IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated'; END IF; END $$;
DROP POLICY IF EXISTS honor_owner_direct ON owner_profiles;
CREATE POLICY honor_owner_direct ON owner_profiles FOR SELECT TO honor_app USING (user_id::text=current_setting('honor.owner_user_id',true) AND active=true);
DROP POLICY IF EXISTS honor_owner_select ON social_identities;
CREATE POLICY honor_owner_select ON social_identities FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON social_accounts;
CREATE POLICY honor_owner_select ON social_accounts FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON campaigns;
CREATE POLICY honor_owner_select ON campaigns FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON uploads;
CREATE POLICY honor_owner_select ON uploads FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON sources;
CREATE POLICY honor_owner_select ON sources FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON transcripts;
CREATE POLICY honor_owner_select ON transcripts FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON generation_runs;
CREATE POLICY honor_owner_select ON generation_runs FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON clips;
CREATE POLICY honor_owner_select ON clips FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON posts;
CREATE POLICY honor_owner_select ON posts FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON submissions;
CREATE POLICY honor_owner_select ON submissions FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON analytics_checkins;
CREATE POLICY honor_owner_select ON analytics_checkins FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON polli_sessions;
CREATE POLICY honor_owner_select ON polli_sessions FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON owner_actions;
CREATE POLICY honor_owner_select ON owner_actions FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON jobs;
CREATE POLICY honor_owner_select ON jobs FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON api_idempotency_records;
CREATE POLICY honor_owner_select ON api_idempotency_records FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON experiments;
CREATE POLICY honor_owner_select ON experiments FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON experiment_arms;
CREATE POLICY honor_owner_select ON experiment_arms FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON experiment_assignments;
CREATE POLICY honor_owner_select ON experiment_assignments FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON account_health_snapshots;
CREATE POLICY honor_owner_select ON account_health_snapshots FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON campaign_terms_snapshots;
CREATE POLICY honor_owner_select ON campaign_terms_snapshots FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON qc_runs;
CREATE POLICY honor_owner_select ON qc_runs FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON analytics_observations;
CREATE POLICY honor_owner_select ON analytics_observations FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON provider_usage;
CREATE POLICY honor_owner_select ON provider_usage FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON polli_turns;
CREATE POLICY honor_owner_select ON polli_turns FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON polli_tool_calls;
CREATE POLICY honor_owner_select ON polli_tool_calls FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON events;
CREATE POLICY honor_owner_select ON events FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON audit_log;
CREATE POLICY honor_owner_select ON audit_log FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON edit_plans;
CREATE POLICY honor_owner_select ON edit_plans FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON audio_plans;
CREATE POLICY honor_owner_select ON audio_plans FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON render_manifests;
CREATE POLICY honor_owner_select ON render_manifests FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON campaign_rule_items;
CREATE POLICY honor_owner_select ON campaign_rule_items FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON run_campaign_allocations;
CREATE POLICY honor_owner_select ON run_campaign_allocations FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON candidates;
CREATE POLICY honor_owner_select ON candidates FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON restriction_proof_artifacts;
CREATE POLICY honor_owner_select ON restriction_proof_artifacts FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON audio_assets;
CREATE POLICY honor_owner_select ON audio_assets FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON backup_runs;
CREATE POLICY honor_owner_select ON backup_runs FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON cost_ledger;
CREATE POLICY honor_owner_select ON cost_ledger FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON source_rights;
CREATE POLICY honor_owner_select ON source_rights FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON source_rights_campaigns;
CREATE POLICY honor_owner_select ON source_rights_campaigns FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON earnings;
CREATE POLICY honor_owner_select ON earnings FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON earning_state_transitions;
CREATE POLICY honor_owner_select ON earning_state_transitions FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON campaign_rule_set_commits;
CREATE POLICY honor_owner_select ON campaign_rule_set_commits FOR SELECT TO honor_app USING (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_select ON accepted_edit_signatures;
CREATE POLICY honor_owner_select ON accepted_edit_signatures FOR SELECT TO honor_app USING (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON social_identities TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON social_identities;
CREATE POLICY honor_owner_insert ON social_identities FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON social_identities;
CREATE POLICY honor_owner_update ON social_identities FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON social_accounts TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON social_accounts;
CREATE POLICY honor_owner_insert ON social_accounts FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON social_accounts;
CREATE POLICY honor_owner_update ON social_accounts FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON campaigns TO honor_app;
GRANT UPDATE(title,currency,canonical_url,updated_at) ON campaigns TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON campaigns;
CREATE POLICY honor_owner_insert ON campaigns FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON campaigns;
CREATE POLICY honor_owner_update ON campaigns FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON uploads TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON uploads;
CREATE POLICY honor_owner_insert ON uploads FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON uploads;
CREATE POLICY honor_owner_update ON uploads FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON sources TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON sources;
CREATE POLICY honor_owner_insert ON sources FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON sources;
CREATE POLICY honor_owner_update ON sources FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON transcripts TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON transcripts;
CREATE POLICY honor_owner_insert ON transcripts FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON transcripts;
CREATE POLICY honor_owner_update ON transcripts FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON generation_runs TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON generation_runs;
CREATE POLICY honor_owner_insert ON generation_runs FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON generation_runs;
CREATE POLICY honor_owner_update ON generation_runs FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON clips TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON clips;
CREATE POLICY honor_owner_insert ON clips FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON clips;
CREATE POLICY honor_owner_update ON clips FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON posts TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON posts;
CREATE POLICY honor_owner_insert ON posts FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON posts;
CREATE POLICY honor_owner_update ON posts FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON submissions TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON submissions;
CREATE POLICY honor_owner_insert ON submissions FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON submissions;
CREATE POLICY honor_owner_update ON submissions FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON analytics_checkins TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON analytics_checkins;
CREATE POLICY honor_owner_insert ON analytics_checkins FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON analytics_checkins;
CREATE POLICY honor_owner_update ON analytics_checkins FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON polli_sessions TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON polli_sessions;
CREATE POLICY honor_owner_insert ON polli_sessions FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON polli_sessions;
CREATE POLICY honor_owner_update ON polli_sessions FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON owner_actions TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON owner_actions;
CREATE POLICY honor_owner_insert ON owner_actions FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON owner_actions;
CREATE POLICY honor_owner_update ON owner_actions FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON jobs TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON jobs;
CREATE POLICY honor_owner_insert ON jobs FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON jobs;
CREATE POLICY honor_owner_update ON jobs FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON api_idempotency_records TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON api_idempotency_records;
CREATE POLICY honor_owner_insert ON api_idempotency_records FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON api_idempotency_records;
CREATE POLICY honor_owner_update ON api_idempotency_records FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON experiments TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON experiments;
CREATE POLICY honor_owner_insert ON experiments FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON experiments;
CREATE POLICY honor_owner_update ON experiments FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON experiment_arms TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON experiment_arms;
CREATE POLICY honor_owner_insert ON experiment_arms FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON experiment_arms;
CREATE POLICY honor_owner_update ON experiment_arms FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT, UPDATE ON experiment_assignments TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON experiment_assignments;
CREATE POLICY honor_owner_insert ON experiment_assignments FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON experiment_assignments;
CREATE POLICY honor_owner_update ON experiment_assignments FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON account_health_snapshots TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON account_health_snapshots;
CREATE POLICY honor_owner_insert ON account_health_snapshots FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON campaign_terms_snapshots TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON campaign_terms_snapshots;
CREATE POLICY honor_owner_insert ON campaign_terms_snapshots FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON qc_runs TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON qc_runs;
CREATE POLICY honor_owner_insert ON qc_runs FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON analytics_observations TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON analytics_observations;
CREATE POLICY honor_owner_insert ON analytics_observations FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON provider_usage TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON provider_usage;
CREATE POLICY honor_owner_insert ON provider_usage FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON polli_turns TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON polli_turns;
CREATE POLICY honor_owner_insert ON polli_turns FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON polli_tool_calls TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON polli_tool_calls;
CREATE POLICY honor_owner_insert ON polli_tool_calls FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON events TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON events;
CREATE POLICY honor_owner_insert ON events FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON audit_log TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON audit_log;
CREATE POLICY honor_owner_insert ON audit_log FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON edit_plans TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON edit_plans;
CREATE POLICY honor_owner_insert ON edit_plans FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON audio_plans TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON audio_plans;
CREATE POLICY honor_owner_insert ON audio_plans FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON render_manifests TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON render_manifests;
CREATE POLICY honor_owner_insert ON render_manifests FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON campaign_rule_items TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON campaign_rule_items;
CREATE POLICY honor_owner_insert ON campaign_rule_items FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON run_campaign_allocations TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON run_campaign_allocations;
CREATE POLICY honor_owner_insert ON run_campaign_allocations FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON candidates TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON candidates;
CREATE POLICY honor_owner_insert ON candidates FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT, INSERT ON restriction_proof_artifacts TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON restriction_proof_artifacts;
CREATE POLICY honor_owner_insert ON restriction_proof_artifacts FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
GRANT SELECT ON owner_profiles TO honor_app;
GRANT SELECT ON audio_assets TO honor_app;
GRANT SELECT ON backup_runs TO honor_app;
GRANT SELECT, INSERT ON cost_ledger TO honor_app;
GRANT UPDATE(actual_cost_usd,reconciled_at) ON cost_ledger TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON cost_ledger;
CREATE POLICY honor_owner_insert ON cost_ledger FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
DROP POLICY IF EXISTS honor_owner_update ON cost_ledger;
CREATE POLICY honor_owner_update ON cost_ledger FOR UPDATE TO honor_app USING (honor_owner_authorized()) WITH CHECK (honor_owner_authorized());
GRANT SELECT ON source_rights TO honor_app;
GRANT SELECT ON source_rights_campaigns TO honor_app;
GRANT SELECT ON earning_state_transitions TO honor_app;
GRANT SELECT ON campaign_rule_set_commits TO honor_app;
GRANT SELECT ON accepted_edit_signatures TO honor_app;
GRANT SELECT, INSERT ON earnings TO honor_app;
DROP POLICY IF EXISTS honor_owner_insert ON earnings;
CREATE POLICY honor_owner_insert ON earnings FOR INSERT TO honor_app WITH CHECK (honor_owner_authorized());
-- PostgreSQL rejects the frozen C00 edit-plan guard body because PL/pgSQL needs
-- parentheses around CASE when it follows IS DISTINCT FROM. The migration runner
-- stores the byte-identical approved C00 definition without validating function
-- bodies; this C01 definition restores immediate validation with identical logic.
CREATE OR REPLACE FUNCTION honor_edit_plan_version_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public,pg_catalog AS $$
DECLARE prev_candidate uuid; prev_version integer; c_source uuid; c_hash char(64); rights_source uuid; rights_hash char(64); camp_id uuid; current_rights uuid; ks knowledge_state_enum; tv jsonb; min_campaign numeric; max_campaign numeric; expected_sec numeric; snap_count integer;
BEGIN
  IF NEW.plan_version=1 THEN IF NEW.supersedes_edit_plan_id IS NOT NULL THEN RAISE EXCEPTION 'edit plan v1 cannot supersede' USING ERRCODE='23514'; END IF;
  ELSE SELECT candidate_id,plan_version INTO prev_candidate,prev_version FROM edit_plans WHERE id=NEW.supersedes_edit_plan_id; IF prev_candidate IS NULL OR prev_candidate<>NEW.candidate_id OR prev_version<>NEW.plan_version-1 THEN RAISE EXCEPTION 'edit_plan predecessor must be same candidate and version N-1' USING ERRCODE='23514'; END IF; END IF;
  SELECT c.source_id,s.sha256 INTO c_source,c_hash FROM candidates c JOIN sources s ON s.id=c.source_id WHERE c.id=NEW.candidate_id;
  IF c_source IS NULL OR c_hash IS NULL THEN RAISE EXCEPTION 'edit plan requires candidate source with immutable source hash' USING ERRCODE='23514'; END IF;
  IF NEW.plan_json->>'candidate_id'<>NEW.candidate_id::text OR NEW.plan_json->>'source_asset_id'<>c_source::text OR NEW.plan_json->>'source_sha256'<>c_hash THEN RAISE EXCEPTION 'edit plan JSON candidate/source fingerprint mismatch' USING ERRCODE='23514'; END IF;
  IF (NEW.plan_json->>'plan_version')::integer<>NEW.plan_version OR NEW.plan_json->>'plan_fingerprint_sha256'<>NEW.plan_hash OR NEW.plan_json->>'supersedes_edit_plan_id' IS DISTINCT FROM (CASE WHEN NEW.supersedes_edit_plan_id IS NULL THEN NULL ELSE NEW.supersedes_edit_plan_id::text END) THEN RAISE EXCEPTION 'edit plan JSON version/hash/supersession mismatch' USING ERRCODE='23514'; END IF;
  SELECT source_id,record_hash INTO rights_source,rights_hash FROM source_rights WHERE id=(NEW.plan_json->>'source_rights_id')::uuid;
  IF rights_source IS NULL OR rights_source<>c_source OR NEW.plan_json->>'source_rights_record_hash'<>rights_hash THEN RAISE EXCEPTION 'edit plan source-rights provenance mismatch' USING ERRCODE='23514'; END IF;
  SELECT count(DISTINCT t.campaign_id) INTO snap_count FROM jsonb_array_elements_text(NEW.plan_json->'campaign_rule_snapshot_ids') x(id_text) JOIN campaign_terms_snapshots t ON t.id=x.id_text::uuid;
  IF snap_count<>1 THEN RAISE EXCEPTION 'edit plan must reference one campaign rule lineage' USING ERRCODE='23514'; END IF;
  SELECT t.campaign_id INTO camp_id FROM jsonb_array_elements_text(NEW.plan_json->'campaign_rule_snapshot_ids') x(id_text) JOIN campaign_terms_snapshots t ON t.id=x.id_text::uuid LIMIT 1;
  IF NEW.plan_json->'rule_compliance'->>'rule_snapshot_id' IS DISTINCT FROM (NEW.plan_json->'campaign_rule_snapshot_ids'->>0) THEN RAISE EXCEPTION 'edit plan rule compliance snapshot mismatch' USING ERRCODE='23514'; END IF;
  current_rights:=honor_current_rights_for_action(c_source,camp_id,NULL,'EDIT_PLAN',NEW.committed_at);
  IF current_rights IS DISTINCT FROM (NEW.plan_json->>'source_rights_id')::uuid THEN RAISE EXCEPTION 'edit plan must use latest applicable rights version at commit time' USING ERRCODE='23514'; END IF;
  FOR ks IN SELECT knowledge_state FROM campaign_rule_items WHERE campaign_id=camp_id AND terms_snapshot_id=(NEW.plan_json->'campaign_rule_snapshot_ids'->>0)::uuid AND rule_key IN ('source_material_restrictions','clip_length_min_seconds','clip_length_max_seconds','content_restrictions','editing_restrictions','uniqueness_rules','render_audio_rules','disclosure_requirements') LOOP IF ks='UNKNOWN' THEN RAISE EXCEPTION 'UNKNOWN critical media rule blocks edit plan' USING ERRCODE='23514'; END IF; END LOOP;
  expected_sec:=(NEW.plan_json->'output'->>'expected_duration_ms')::numeric/1000.0;
  SELECT CASE WHEN knowledge_state='KNOWN' THEN (typed_value->>'value')::numeric END INTO min_campaign FROM campaign_rule_items WHERE campaign_id=camp_id AND terms_snapshot_id=(NEW.plan_json->'campaign_rule_snapshot_ids'->>0)::uuid AND rule_key='clip_length_min_seconds';
  SELECT CASE WHEN knowledge_state='KNOWN' THEN (typed_value->>'value')::numeric END INTO max_campaign FROM campaign_rule_items WHERE campaign_id=camp_id AND terms_snapshot_id=(NEW.plan_json->'campaign_rule_snapshot_ids'->>0)::uuid AND rule_key='clip_length_max_seconds';
  IF min_campaign IS NOT NULL AND expected_sec<min_campaign THEN RAISE EXCEPTION 'edit plan duration below campaign minimum' USING ERRCODE='23514'; END IF;
  IF max_campaign IS NOT NULL AND expected_sec>max_campaign THEN RAISE EXCEPTION 'edit plan duration above campaign maximum' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION honor_edit_plan_version_guard() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION honor_edit_plan_version_guard() TO honor_app;
-- C01 mechanical realization of the frozen one-time cost reconciliation guard.
CREATE OR REPLACE FUNCTION c01_cost_ledger_reconciliation_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path=public,pg_catalog AS $$
DECLARE
  audit_request_id uuid;
BEGIN
  IF TG_OP <> 'UPDATE' THEN
    RAISE EXCEPTION 'cost ledger history is immutable' USING ERRCODE='42501';
  END IF;
  IF OLD.actual_cost_usd IS NOT NULL OR OLD.reconciled_at IS NOT NULL
     OR NEW.actual_cost_usd IS NULL OR NEW.reconciled_at IS NULL THEN
    RAISE EXCEPTION 'cost reconciliation is one-time NULL-to-value only' USING ERRCODE='42501';
  END IF;
  IF (to_jsonb(NEW) - ARRAY['actual_cost_usd','reconciled_at'])
     IS DISTINCT FROM
     (to_jsonb(OLD) - ARRAY['actual_cost_usd','reconciled_at']) THEN
    RAISE EXCEPTION 'only reconciliation fields may change' USING ERRCODE='42501';
  END IF;
  audit_request_id := COALESCE(
    NULLIF(current_setting('honor.request_id', true),'')::uuid,
    gen_random_uuid()
  );
  INSERT INTO audit_log(
    id,occurred_at,actor_type,actor_id,action,target_type,target_id,request_id,metadata_redacted
  ) VALUES(
    gen_random_uuid(),statement_timestamp(),'OWNER_RUNTIME',
    NULLIF(current_setting('honor.owner_user_id', true),'')::uuid,
    'COST_LEDGER_RECONCILED','cost_ledger',NEW.id,audit_request_id,
    jsonb_build_object('provider',NEW.provider,'service',NEW.service)
  );
  RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION c01_cost_ledger_reconciliation_guard() FROM PUBLIC;
DROP TRIGGER IF EXISTS trg_c01_cost_ledger_reconciliation_guard ON cost_ledger;
CREATE TRIGGER trg_c01_cost_ledger_reconciliation_guard
BEFORE UPDATE ON cost_ledger
FOR EACH ROW EXECUTE FUNCTION c01_cost_ledger_reconciliation_guard();

DO $do$ DECLARE r record; BEGIN FOR r IN SELECT p.oid::regprocedure AS sig FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname LIKE 'honor_%' LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',r.sig); EXECUTE format('REVOKE ALL ON FUNCTION %s FROM honor_app',r.sig); END LOOP; END $do$;
GRANT EXECUTE ON FUNCTION honor_00_clip_recommendation_revision_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_00_experiment_arm_identity_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_00_experiment_row_identity_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_01_posting_restriction_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_absolute_uri(text) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_activate_campaign_rule_snapshot(uuid, uuid) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_allocation_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_audio_allowed_uses_valid(jsonb) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_audio_asset_contract_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_audio_asset_render_eligible(uuid, platform_enum) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_audio_plan_asset_rights_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_audio_plan_version_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_audio_rule_enforcement_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_campaign_mirror_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_campaign_rule_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_campaign_rule_typed_value_valid(text, jsonb) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_candidate_lineage_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_clip_cross_record_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_clip_provenance_lock_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_clip_ready_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_clip_render_start_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_commit_source_rights_version(uuid, uuid, integer, uuid, source_eligibility_enum, jsonb, jsonb, text, text, text, timestamptz, timestamptz, text, text, uuid[]) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_current_rights_for_action(uuid, uuid, platform_enum, text, timestamptz) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_disclosure_deadline_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_earning_lineage_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_edit_plan_version_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_experiment_history_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_experiment_reference_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_final_uniqueness_acceptance_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_generation_run_history_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_internal_action_time_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_jsonb_exact_keys(jsonb, text[]) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_lifecycle_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_owner_action_lifecycle_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_owner_action_resolution_valid(text, text, uuid, jsonb) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_owner_authorized() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_post_publish_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_qc_truth_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_reject_immutable_mutation() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_render_audio_disclosure_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_render_manifest_action_rights_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_render_manifest_audio_asset_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_render_manifest_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_render_start_audio_asset_rights_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_restriction_compliance_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_restriction_consumes_stage(text, text) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_restriction_proof_artifact_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_rfc3339_datetime(text) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_rights_stage_allowed(uuid, uuid, platform_enum, text, timestamptz) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_round10_restriction_placement_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_rule_set_consumption_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_rule_set_runtime_schema_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_rule_set_sealed_for_action(uuid, uuid, integer, timestamptz) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_seal_campaign_rule_set(uuid, uuid, integer) TO honor_app;
GRANT EXECUTE ON FUNCTION honor_single_rule_set_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_source_rights_version_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_submission_lineage_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_transcript_guard() TO honor_app;
GRANT EXECUTE ON FUNCTION honor_transition_earning(uuid, earning_state_enum, timestamptz, text, text, text, text) TO honor_app;
REVOKE DELETE ON ALL TABLES IN SCHEMA public FROM honor_app;
